# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.public
        - ./.theme/.temp
        - ./.theme/content
  - touch:
      path: ./.theme/.env.local

  # Copy images to .public
  - copy:
      extension: .png
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .jpg
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .svg
      source: ./
      target: ./.theme/.public
  # Copy all files in public to .public
  - copy:
      source: ./.theme/public
      target: ./.theme/.public

  # Extract diagrams
  - extractDiagrams:
      source: ./
      target: ./.theme/.temp
      config:
        backgroundColor: '#092C2E'
        outputFormat: svg
        theme: base
        deviceScaleFactor: 1
        headless: new
        flowchart:
          useMaxWidth: false
        themeVariables:
          primaryColor: '#FA465B'
          primaryTextColor: '#F7F7F7'
          primaryBorderColor': '#FA465B'
          lineColor: '#D5DBDB'
          secondaryColor: '#031819'
          secondaryTextColor: '#E9EBEB'
          secondaryBorderColor: '#031819'
          tertiaryColor: '#154245'
          activationBkgColor: '#FA465B'
  - move:
      extension: .svg
      source: ./.theme/.temp
      target: ./.theme/.public
  - move:
      extension: .md
      source: ./.theme/.temp
      target: ./.theme/content
