# Project root relative to this config file
projectRoot: ../../

# Log settings
log:
  debug: false # Enable debug logs
  quiet: false # Disable logs completely

# Tasks to run in given order
tasks:
  - clean:
      directories:
        - ./.theme/.public
        - ./.theme/.temp
        - ./.theme/content
  - touch:
      path: ./.theme/.env.local

  # Copy images to .public
  - copy:
      extension: .png
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .jpg
      source: ./
      target: ./.theme/.public
  - copy:
      extension: .svg
      source: ./
      target: ./.theme/.public
  # Copy all files in public to .public
  - copy:
      source: ./.theme/public
      target: ./.theme/.public

  # Extract diagrams
  - extractDiagrams:
      source: ./
      target: ./.theme/.temp
      config:
        backgroundColor: '#092122'
        outputFormat: svg
        theme: base
        deviceScaleFactor: 1
        headless: new
        themeVariables:
          fontFamily: '"Roboto Mono", monospace'
          fontSize: '16px'
          primaryColor: '#fa465b'
          primaryTextColor: '#f6f6f6'
          primaryBorderColor': '#fa465b'
          lineColor: '#888888'
          secondaryColor: '#061819'
          secondaryTextColor: '#cacaca'
          secondaryBorderColor: '#061819'
          tertiaryColor: '#163738'
          activationBkgColor: '#fa465b'
  - move:
      extension: .svg
      source: ./.theme/.temp
      target: ./.theme/.public
  - move:
      extension: .md
      source: ./.theme/.temp
      target: ./.theme/content
