name: Publish
on:
  push:
    branches:
      - main
      - 'issue/**'
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Build Docs
        run: |
          cd .theme/
          npm install
          npm run generate:production
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: .theme/.output/public
          if-no-files-found: error
          include-hidden-files: true
  publish:
    needs: generate
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: deploy
      - name: Remove Old Files
        run: |
          git rm -rf .
          git clean -fxd
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: docs
      - name: Commit & Push
        run: |
          git config user.name 'github-actions'
          git config user.email 'github-actions@users.noreply.github.com'
          git add -A
          git commit -m 'deploy to github pages'
          git push -f
