name: Regular Checks
on:
  pull_request:
    branches:
      - main
      - 'epic/**'
jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Generate
        run: |
          cd ./.theme/
          npm install
          npm run generate:production
